data = [
    ### GMAP
    {
        'field_name': 'business_is_category_herbs',
        'field_query': 'is about medicinal plants', 
        'field_description': '''that deals with herbs''', 
        'field_type': 'bool',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_name_raw',
        'field_query': 'business name', 
        'field_description': '''business name as shown on the website''', 
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_website',
        'field_query': 'business website', 
        'field_description': '''The official website URL of the business. Extract the primary canonical domain used by the organization (e.g., https://www.example.com).''', 
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_website_html',
        'field_query': 'business website_html', 
        'field_description': '''''', 
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_website_text',
        'field_query': 'business website_text', 
        'field_description': '''''', 
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_address',
        'field_query': 'business address', 
        'field_description': '''The complete street address of the business's primary location, including building number, street name, and other published address details.''', 
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_phone',
        'field_query': 'business phone', 
        'field_description': '''The primary business telephone number for customer inquiries. Preserve the international dialing code when available.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_rating',
        'field_query': '', 
        'field_description': '''''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_reviews_num',
        'field_query': '', 
        'field_description': '''''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_map',
        'field_query': '', 
        'field_description': '''''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    ### IDENTITY
    {
        'field_name': 'business_name_official',
        'field_query': 'official business name', 
        'field_description': '''Official business name exactly as shown on the website''', 
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_name_legal',
        'field_query': 'legal business name', 
        'field_description': '''Registered legal business name if published''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_name_trade',
        'field_query': 'trading business name', 
        'field_description': '''Public trading or DBA name''', 
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_company_type',
        'field_query': 'business company type', 
        'field_description': '''Private, public, cooperative, nonprofit, family-owned, etc.''', 
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_ownership_type',
        'field_query': 'business ownership type', 
        'field_description': '''LLC, Ltd, Inc., GmbH, Cooperative, etc.''', 
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_slogan',
        'field_query': 'business slogan', 
        'field_description': '''Official company slogan or tagline''', 
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_description',
        'field_query': 'business description', 
        'field_description': '''Main factual description of the company''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_description_short',
        'field_query': 'short business description', 
        'field_description': '''Short summary (1–2 sentences)''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },

    {
        'field_name': 'business_type_primary',
        'field_query': 'primary business type', 
        'field_description': '''Main business role''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_type_secondary',
        'field_query': 'secondary business type', 
        'field_description': '''Additional business role''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_industry',
        'field_query': 'business industry', 
        'field_description': '''Industry classification''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_niche',
        'field_query': 'business niche', 
        'field_description': '''Specific medicinal plant niche''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_model',
        'field_query': 'business model', 
        'field_description': '''B2B, B2C, Marketplace, Manufacturer, etc.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_status',
        'field_query': 'business status', 
        'field_description': '''Active, acquired, merged, closed, etc.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },

    {
        'field_name': 'business_founding_year',
        'field_query': 'business founding year', 
        'field_description': '''Year the business was founded''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_founding_story',
        'field_query': 'business founding story', 
        'field_description': '''History or origin story''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_founder_names',
        'field_query': 'business founder names', 
        'field_description': '''Name(s) of the founder(s)''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_mission',
        'field_query': 'business mission', 
        'field_description': '''Mission statement''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_vision',
        'field_query': 'business vision', 
        'field_description': '''Vision statement''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_core_values',
        'field_query': 'business core values', 
        'field_description': '''Company's stated values''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },

    ### 3. LOCATION
    {
        'field_name': 'business_headquarters',
        'field_query': 'business headquarters', 
        'field_description': '''The primary headquarters location of the business, including the city and country where the company is officially based.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_city',
        'field_query': 'business city', 
        'field_description': '''The city or municipality where the business or facility is located.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_state',
        'field_query': 'business state', 
        'field_description': '''The state, province, prefecture, or equivalent first-level administrative division where the business is located.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_region',
        'field_query': 'business region', 
        'field_description': '''The broader geographic or administrative region (e.g., Tuscany, Bavaria, Queensland) where the business operates.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_country',
        'field_query': 'business country', 
        'field_description': '''The country where the business's primary location is situated. Store using a standardized country name or ISO country code.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_postal_code',
        'field_query': 'business postal code', 
        'field_description': '''The postal or ZIP code associated with the business's address.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_latitude',
        'field_query': 'business latitude', 
        'field_description': '''The latitude coordinate of the published business location, if explicitly available on the website.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_longitude',
        'field_query': 'business longitude', 
        'field_description': '''The longitude coordinate of the published business location, if explicitly available on the website.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_additional_locations',
        'field_query': 'business additional locations', 
        'field_description': '''Other business locations, offices, branches, or facilities operated by the company besides its headquarters. Include names and addresses when available.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_farm_locations',
        'field_query': 'business farm locations', 
        'field_description': '''Locations of farms where the business cultivates, grows, or harvests medicinal plants. Include addresses or geographic areas if provided.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_nursery_locations',
        'field_query': 'business nursery locations', 
        'field_description': '''Locations of plant nurseries where medicinal plants, seedlings, or seeds are propagated or sold.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_factory_locations',
        'field_query': 'business factory locations', 
        'field_description': '''Locations of manufacturing or production facilities where medicinal plant products are processed, formulated, packaged, or manufactured.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_laboratory_locations',
        'field_query': 'business laboratory locations', 
        'field_description': '''Locations of laboratories used for research, quality control, testing, extraction, or scientific analysis.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_warehouse_locations',
        'field_query': 'business warehouse locations', 
        'field_description': '''Locations of warehouses, storage facilities, fulfillment centers, or distribution centers used by the business.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_retail_locations',
        'field_query': 'business retail locations', 
        'field_description': '''Physical retail stores, herbal shops, apothecaries, garden centers, or showrooms operated by the business where customers can make purchases.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },

    ### 4. VISITOR
    {
        'field_name': 'business_opening_hours',
        'field_query': 'business opening hours', 
        'field_description': '''The regular hours during which the business is open to visitors or customers.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_seasonal_hours',
        'field_query': 'business seasonal hours', 
        'field_description': '''Any changes to the business opening hours that apply during specific seasons, holidays, or periods of the year.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_appointment_required',
        'field_query': 'business appointment required', 
        'field_description': '''Whether visitors or customers are required to make an appointment in advance.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_walk_in_available',
        'field_query': 'business walk in available', 
        'field_description': '''Whether visitors or customers can visit without an appointment or prior booking.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_visitor_access',
        'field_query': 'business visitor access', 
        'field_description': '''Information about whether and how visitors can access the business or its premises, including any restrictions or requirements.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },

    ### 5. MEDICINAL PLANTS
    {
        'field_name': 'business_medicinal_plants',
        'field_query': 'business medicinal plants', 
        'field_description': '''Comprehensive list of medicinal plants, herbs, trees, shrubs, or other botanicals mentioned on the website''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_primary_medicinal_plants',
        'field_query': 'business primary medicinal plants', 
        'field_description': '''Main medicinal plants that are prominently featured, emphasized, or central to the organization's work or offerings''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_specialty_plants',
        'field_query': 'business specialty plants', 
        'field_description': '''Specialty, flagship, signature, or particularly notable plant species associated with the organization''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_native_plants',
        'field_query': 'business native plants', 
        'field_description': '''Medicinal plant species identified as native to the region, country, or geographic area discussed''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_rare_plants',
        'field_query': 'business rare plants', 
        'field_description': '''Rare, threatened, endangered, vulnerable, or otherwise conservation-significant medicinal plant species mentioned''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_medicinal_plant_categories',
        'field_query': 'business medicinal plant categories', 
        'field_description': '''Categories or groupings of medicinal plants mentioned, such as adaptogens, aromatic herbs, medicinal trees, roots, flowers, or traditional herbal plants''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_botanical_collection_size',
        'field_query': 'business botanical collection size', 
        'field_description': '''Number of medicinal or botanical plant species in the organization's collection, garden, archive, nursery, or other stated botanical holdings, if specified''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },

    ### 6. BOTANICAL ACTIVITIES
    {
        'field_name': 'business_grows',
        'field_query': 'business grows', 
        'field_description': '''Whether the business grows or cultivates plants, crops, or other botanical species itself.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_cultivates',
        'field_query': 'business cultivates', 
        'field_description': '''Whether the business actively cultivates plants or botanical species through managed growing practices.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_propagates',
        'field_query': 'business propagates', 
        'field_description': '''Whether the business propagates plants, such as through seeds, cuttings, division, tissue culture, or other propagation methods.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_researches',
        'field_query': 'business researches', 
        'field_description': '''Whether the business conducts or supports research involving plants, botanical species, cultivation, or related applications.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_sells',
        'field_query': 'business sells', 
        'field_description': '''Whether the business sells plants, botanical materials, or plant-derived products directly to customers.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_distributes',
        'field_query': 'business distributes', 
        'field_description': '''Whether the business distributes plants, botanical materials, or plant-derived products to retailers, businesses, or other organizations.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_exports',
        'field_query': 'business exports', 
        'field_description': '''Whether the business exports plants, botanical materials, or plant-derived products to other countries.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_imports',
        'field_query': 'business imports', 
        'field_description': '''Whether the business imports plants, botanical materials, or plant-derived products from other countries.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_wild_harvests',
        'field_query': 'business wild harvests', 
        'field_description': '''Whether the business collects plants or botanical materials from wild or naturally occurring populations.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_conserves',
        'field_query': 'business conserves', 
        'field_description': '''Whether the business engages in plant conservation, preservation, habitat protection, or safeguarding of botanical biodiversity.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_teaches',
        'field_query': 'business teaches', 
        'field_description': '''Whether the business provides education, training, workshops, courses, or other instruction related to plants, cultivation, or botanical practices.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_uses_in_products',
        'field_query': 'business uses in products', 
        'field_description': '''Whether the business uses plants, botanical materials, or plant-derived ingredients in products it manufactures or offers.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },

    ### 7. PRODUCTS
    {
        'field_name': 'business_products_herbs',
        'field_query': 'business herbs products', 
        'field_description': '''List of herbs this business deal with.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_products',
        'field_query': 'business products', 
        'field_description': '''Comprehensive information about all herbal and natural health products offered, including formulations, uses, and availability.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_products_categories',
        'field_query': 'business products categories', 
        'field_description': '''Overview of the different product categories available, including how products are organized by type or purpose.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_products_flagship',
        'field_query': 'business flagship products', 
        'field_description': '''Information about featured, best-selling, or signature products that represent the business's core offerings.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_products_forms',
        'field_query': 'business products forms', 
        'field_description': '''Details about the various forms in which products are available, such as teas, tinctures, capsules, powders, oils, and creams.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },

    ### 10. SERVICES
    {
        'field_name': 'business_herbal_consultation',
        'field_query': 'business herbal consultation', 
        'field_description': '''Professional consultation services focused on the traditional, therapeutic, or practical use of herbs and medicinal plants.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_herbal_clinic',
        'field_query': 'business herbal clinic', 
        'field_description': '''A clinic or practice providing consultations and services related to herbal medicine and plant-based wellness.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_medicinal_plant_consulting',
        'field_query': 'business medicinal plant consulting', 
        'field_description': '''Expert advice on the selection, use, cultivation, sourcing, processing, or commercialization of medicinal plants.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_plant_identification',
        'field_query': 'business plant identification', 
        'field_description': '''Services for identifying plant species, varieties, or specimens based on their physical or botanical characteristics.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_botanical_identification',
        'field_query': 'business botanical identification', 
        'field_description': '''Specialized identification and classification of plants using botanical taxonomy and scientific methods.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_cultivation_consulting',
        'field_query': 'business cultivation consulting', 
        'field_description': '''Consulting services covering the cultivation, propagation, growing conditions, harvesting, and management of plants.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_contract_growing',
        'field_query': 'business contract growing', 
        'field_description': '''Growing plants or agricultural crops on behalf of another business under an agreed contract or production arrangement.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_contract_manufacturing',
        'field_query': 'business contract manufacturing', 
        'field_description': '''Manufacturing botanical, herbal, or plant-based products on behalf of another company or brand.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_private_label_manufacturing',
        'field_query': 'business private label manufacturing', 
        'field_description': '''Production of herbal, botanical, or plant-based products that are sold under a customer's own brand or private label.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_extraction_services',
        'field_query': 'business extraction services', 
        'field_description': '''Services for extracting active compounds, oils, or other useful constituents from plants or botanical materials.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_drying_services',
        'field_query': 'business drying services', 
        'field_description': '''Commercial drying of harvested plants, herbs, roots, leaves, flowers, or other botanical materials to preserve and prepare them for further use.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_milling',
        'field_query': 'business milling', 
        'field_description': '''Mechanical processing of plant or botanical materials into smaller particles or a desired particle size.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_grinding',
        'field_query': 'business grinding', 
        'field_description': '''Processing herbs, plants, seeds, roots, or other botanical materials into a coarse or fine ground form.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_packaging_service',
        'field_query': 'business packaging service', 
        'field_description': '''Packaging services for herbal, botanical, agricultural, or plant-based products in suitable containers or formats.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_export_services',
        'field_query': 'business export services', 
        'field_description': '''Services supporting the preparation, documentation, logistics, and international shipment of botanical or plant-based products.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_laboratory_testing',
        'field_query': 'business laboratory testing', 
        'field_description': '''Laboratory analysis and testing of botanical or herbal materials and products for quality, identity, purity, safety, or composition.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_formulation',
        'field_query': 'business formulation', 
        'field_description': '''Development or preparation of recipes and product formulations using herbs, botanicals, extracts, or other plant-based ingredients.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_research_services',
        'field_query': 'business research services', 
        'field_description': '''Research and development services involving medicinal plants, botanicals, herbal products, cultivation, extraction, or related scientific topics.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_education',
        'field_query': 'business education', 
        'field_description': '''Educational services providing knowledge or training related to herbs, medicinal plants, botany, cultivation, processing, or herbal practices.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_workshops',
        'field_query': 'business workshops', 
        'field_description': '''Practical, focused educational sessions or hands-on activities covering herbal, botanical, cultivation, processing, or related topics.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_courses',
        'field_query': 'business courses', 
        'field_description': '''Structured educational programs providing systematic instruction in herbal medicine, botany, plant cultivation, or related subjects.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_farm_tours',
        'field_query': 'business farm tours', 
        'field_description': '''Guided visits to farms or agricultural operations where participants can learn about plant cultivation, harvesting, and production.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_botanical_tours',
        'field_query': 'business botanical tours', 
        'field_description': '''Guided tours focused on identifying, studying, and learning about botanical species and plant collections in natural or cultivated settings.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
]
