data = [
    {
        'field_name': 'business_is_category_herbs',
        'field_query': 'is about medicinal plants', 
        'field_description': '''that deals with herbs''', 
        'field_type': 'bool',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_name_raw',
        'field_query': 'business name', 
        'field_description': '''business name as shown on the website''', 
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_name_official',
        'field_query': 'official business name', 
        'field_description': '''Official business name exactly as shown on the website''', 
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_slogan',
        'field_query': 'business slogan', 
        'field_description': '''Official company slogan or tagline''', 
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_website',
        'field_query': 'business website', 
        'field_description': '''The official website URL of the business. Extract the primary canonical domain used by the organization (e.g., https://www.example.com).''', 
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_address',
        'field_query': 'business address', 
        'field_description': '''The complete street address of the business's primary location, including building number, street name, and other published address details.''', 
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_phone',
        'field_query': 'business phone', 
        'field_description': '''The primary business telephone number for customer inquiries. Preserve the international dialing code when available.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_rating',
        'field_query': '', 
        'field_description': '''''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_reviews_num',
        'field_query': '', 
        'field_description': '''''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_type_primary',
        'field_query': 'primary business type', 
        'field_description': '''Main business role''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_map',
        'field_query': '', 
        'field_description': '''''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_description',
        'field_query': 'business description', 
        'field_description': '''Main factual description of the company''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_description_short',
        'field_query': 'short business description', 
        'field_description': '''Short summary (1–2 sentences)''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_founding_year',
        'field_query': 'business founding year', 
        'field_description': '''Year the business was founded''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_founding_story',
        'field_query': 'business founding story', 
        'field_description': '''History or origin story''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },

    {
        'field_name': 'business_products_herbs',
        'field_query': 'business herbs products', 
        'field_description': '''List of herbs this business deal with.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
    {
        'field_name': 'business_products',
        'field_query': 'business products', 
        'field_description': '''Comprehensive information about all herbal and natural health products offered, including formulations, uses, and availability.''',
        'field_type': 'text',
        'field_section': 'identity',
        'regen': False,
    },
]
