def synonym_create(
    plant_name_raw, 
    plant_synonym_raw, 
    source_name,
):
    item = {
        'plant_name_raw': plant_name_raw,
        'plant_synonym_raw': plant_synonym_raw,
        'source_name': source_name,
    }
    return item

def plant_part_create(
    plant_name_raw,
    plant_part_name_raw,
    source_name,
    source_acronym,
    reference_name,
):
    item = {
        'plant_name_raw': plant_name_raw,
        'plant_part_name_raw': plant_part_name_raw,
        'source_name': source_name,
        'source_acronym': source_acronym,
        'reference_name': reference_name,
    }
    return item

def activity_create(
    plant_name_raw,
    activity_name_raw,
    source_name,
    source_acronym,
    reference_name,
):
    item = {
        'plant_name_raw': plant_name_raw,
        'activity_name_raw': activity_name_raw,
        'source_name': source_name,
        'source_acronym': source_acronym,
        'reference_name': reference_name,
    }
    return item

def chemical_create(
    plant_name_raw, 
    chemical_name_raw, 
    plant_part_name_raw, 
    source_name,
    source_acronym,
    reference_name,
):
    if plant_part_name_raw == None: plant_part_name_raw = ''
    if plant_part_name_raw.lower() == 'null': plant_part_name_raw = ''
    item = {
        'plant_name_raw': plant_name_raw,
        'chemical_name_raw': chemical_name_raw,
        'plant_part_name_raw': plant_part_name_raw,
        'source_name': source_name,
        'source_acronym': source_acronym,
        'reference_name': reference_name,
    }
    return item


def common_name_create(
    plant_name_scientific_raw,
    plant_name_scientific_norm,
    plant_name_common_raw,
    plant_name_common_transliteration,
    plant_name_common_language,
    plant_name_common_preferred,
    plant_name_common_country,
    plant_name_common_area,
    plant_name_common_type,
    source_name,
    source_acronym,
):
    item = {
        'plant_name_scientific_raw': plant_name_scientific_raw,
        'plant_name_scientific_norm': plant_name_scientific_norm,
        'plant_name_common_raw': plant_name_common_raw,
        'plant_name_common_transliteration': plant_name_common_transliteration,
        'plant_name_common_language': plant_name_common_language,
        'plant_name_common_preferred': plant_name_common_preferred,
        'plant_name_common_country': plant_name_common_country,
        'plant_name_common_area': plant_name_common_area,
        'plant_name_common_type': plant_name_common_type,
        'source_name': source_name,
        'source_acronym': source_acronym,
    }
    return item

def trait_create(
    plant_name_scientific_raw,
    plant_name_scientific_norm,
    plant_genus,
    plant_author,
    trait_category,
    trait_1,
    trait_2,
    trait_units,
    trait_type,
    trait_value,
    trait_agreement,
    trait_coeff_var,
    trait_n,
    trait_refs,
    source_name,
    source_acronym,
):
    item = {
        'plant_name_scientific_raw': plant_name_scientific_raw,
        'plant_name_scientific_norm': plant_name_scientific_norm,
        'plant_genus': plant_genus,
        'plant_author': plant_author,
        'trait_category': trait_category,
        'trait_1': trait_1,
        'trait_2': trait_2,
        'trait_units': trait_units,
        'trait_type': trait_type,
        'trait_value': trait_value,
        'trait_agreement': trait_agreement,
        'trait_coeff_var': trait_coeff_var,
        'trait_n': trait_n,
        'trait_refs': trait_refs,
        'source_name': source_name,
        'source_acronym': source_acronym,
    }
    return item

def organizations__business_create(
    business_is_category_herbs,

    business_label,
    business_name,
    business_name_official,
    business_name_legal,
    business_name_trade,
    business_slogan,
    business_description,
    business_description_short,
    business_founded_year,
    business_founding_story,
    business_founder_names,
    business_ownership_type,
    business_company_type,
    business_status,
    business_mission,
    business_vision,
    business_core_values,
    ###
    business_type_primary,
    business_type_secondary,
    business_industry,
    business_niche,
    business_model,
    ###
    business_website,
    business_email,
    business_email_customer_service,
    business_email_wholesale,
    business_email_media,
    business_phone,
    business_whatsapp,
    business_fax,
    business_contact_form,
    ###
    business_headquarters,
    business_address,
    business_city,
    business_state,
    business_region,
    business_country,
    business_postal_code,
    business_latitude,
    business_longitude,
    business_additional_locations,
    business_farm_locations,
    business_nursery_locations,
    business_factory_locations,
    business_laboratory_locations,
    business_warehouse_locations,
    business_retail_locations,
    ###
    business_opening_hours,
    business_seasonal_hours,
    business_appointment_required,
    business_walk_in_available,
    business_visitor_access,
    ###
    business_medicinal_plants,
    business_primary_medicinal_plants,
    business_specialty_plants,
    business_native_plants,
    business_rare_plants,
    business_medicinal_plant_categories,
    business_botanical_collection_size,
    ###
    business_grows,
    business_cultivates,
    business_propagates,
    business_researches,
    business_sells,
    business_distributes,
    business_exports,
    business_imports,
    business_wild_harvests,
    business_conserves,
    business_teaches,
    business_uses_in_products,
    ###
    business_products,
    business_product_categories,
    business_flagship_products,
    business_product_forms,
    business_herbal_teas,
    business_tinctures,
    business_extracts,
    business_essential_oils,
    business_capsules,
    business_powders,
    business_dried_herbs,
    business_fresh_herbs,
    business_seeds,
    business_seedlings,
    business_roots,
    business_bark,
    business_flowers,
    business_fruits,
    business_resins,
    business_cosmetics,
    business_soaps,
    business_creams,
    business_salves,
    business_syrups,
    ###
    business_botanical_name,
    business_common_name,
    business_plant_part,
    business_extraction_method,
    business_preparation_method,
    business_ingredients,
    business_packaging,
    business_package_sizes,
    business_concentration,
    business_organic_product,
    business_private_label,
    business_wholesale,
    business_retail,
    ###
    business_herbal_consultation,
    business_herbal_clinic,
    business_medicinal_plant_consulting,
    business_plant_identification,
    business_botanical_identification,
    business_cultivation_consulting,
    business_contract_growing,
    business_contract_manufacturing,
    business_private_label_manufacturing,
    business_extraction_services,
    business_drying_services,
    business_milling,
    business_grinding,
    business_packaging_service,
    business_export_services,
    business_laboratory_testing,
    business_formulation,
    business_research_services,
    business_education,
    business_workshops,
    business_courses,
    business_farm_tours,
    business_botanical_tours,

    business_cultivation_methods,
    business_organic_cultivation,
    business_regenerative,
    business_biodynamic,
    business_permaculture,
    business_agroforestry,
    business_greenhouse,
    business_indoor,
    business_outdoor,
    business_wild_harvesting,
    business_sustainable_wild_harvesting,
    business_propagation_methods,
    business_irrigation,
    business_fertilization,
    business_soil_management,
    business_pest_management,
    business_harvest_methods,
    business_harvest_season,

    business_manufacturing,
    business_processing,
    business_extraction,
    business_distillation,
    business_fermentation,
    business_drying,
    business_manufacturing_milling,
    business_manufacturing_grinding,
    business_blending,
    business_manufacturing_formulation,
    business_encapsulation,
    business_manufacturing_packaging,
    business_quality_testing,
    business_batch_testing,
    business_traceability,

    business_facilities_farms,
    business_facilities_nurseries,
    business_facilities_laboratories,
    business_facilities_factories,
    business_facilities_warehouses,
    business_facilities_botanical_gardens,
    business_facilities_greenhouses,
    business_facilities_visitor_centers,
    business_facilities_research_centers,
    business_facilities_education_centers,
    business_facilities_clinics,
    business_facilities_retail_stores,

    business_certifications_certifications,
    business_certifications_certification_name,
    business_certifications_certification_number,
    business_certifications_issuing_organization,
    business_certifications_issue_date,
    business_certifications_expiry_date,
    business_certifications_certification_scope,

    business_quality_quality_control,
    business_quality_laboratory_testing,
    business_quality_batch_testing,
    business_quality_third_party_testing,
    business_quality_traceability,
    business_quality_quality_management_system,

    business_sustainability_sustainability_policy,
    business_sustainability_conservation,
    business_sustainability_biodiversity,
    business_sustainability_regenerative_agriculture,
    business_sustainability_ethical_sourcing,
    business_sustainability_fair_trade,
    business_sustainability_community_projects,
    business_sustainability_indigenous_partnerships,
    business_sustainability_local_sourcing,
    business_sustainability_recyclable_packaging,
    business_sustainability_carbon_reduction,
    business_sustainability_water_conservation,

    business_research_research_programs,
    business_research_research_projects,
    business_research_publications,
    business_research_patents,
    business_research_university_partnerships,
    business_research_clinical_trials,
    business_research_ethnobotanical_research,
    business_research_pharmacognosy,
    business_research_phytochemistry,
    business_research_plant_breeding,

    business_education_courses,
    business_education_workshops,
    business_education_webinars,
    business_education_apprenticeships,
    business_education_lectures,
    business_education_botanical_walks,
    business_education_farm_tours,
    business_education_certifications_offered,

    business_traditional_medicine_systems_ayurveda,
    business_traditional_medicine_systems_traditional_chinese_medicine,
    business_traditional_medicine_systems_western_herbalism,
    business_traditional_medicine_systems_unani,
    business_traditional_medicine_systems_kampo,
    business_traditional_medicine_systems_tibetan_medicine,
    business_traditional_medicine_systems_indigenous_medicine,
    business_traditional_medicine_systems_african_traditional_medicine,

    business_expertise_expertise_topics,
    business_expertise_medicinal_plant_cultivation,
    business_expertise_herbal_formulation,
    business_expertise_ethnobotany,
    business_expertise_pharmacognosy,
    business_expertise_botanical_identification,
    business_expertise_herbal_medicine,
    business_expertise_conservation,
    business_expertise_plant_propagation,

    business_people_founders,
    business_people_owners,
    business_people_ceo,
    business_people_president,
    business_people_director,
    business_people_botanists,
    business_people_herbalists,
    business_people_researchers,
    business_people_agronomists,
    business_people_pharmacists,
    business_people_educators,
    business_people_laboratory_directors,
    business_people_farm_managers,

    business_markets_customer_types,
    business_markets_industries_served,
    business_markets_export_markets,
    business_markets_import_markets,
    business_markets_countries_served,
    business_markets_regions_served,
    business_markets_international_shipping,
    business_markets_wholesale_available,
    business_markets_retail_available,
    business_markets_private_label_available,

    business_online_presence_facebook,
    business_online_presence_instagram,
    business_online_presence_linkedin,
    business_online_presence_youtube,
    business_online_presence_x,
    business_online_presence_pinterest,
    business_online_presence_tiktok,
    business_online_presence_github,
    business_online_presence_wikipedia,

    business_awards_awards,
    business_awards_award_name,
    business_awards_award_year,
    business_awards_awarding_organization,

    business_memberships_professional_associations,
    business_memberships_industry_memberships,
    business_memberships_botanical_societies,
    business_memberships_herbal_associations,

    business_policies_privacy_policy,
    business_policies_shipping_policy,
    business_policies_returns_policy,
    business_policies_refund_policy,
    business_policies_sustainability_policy,
    business_policies_accessibility_policy,

    business_languages_languages,
    business_languages_multilingual_support,

    business_commerce_accepted_payment_methods,
    business_commerce_currencies,
    business_commerce_online_store,
    business_commerce_ecommerce,

    business_shipping_shipping_countries,
    business_shipping_shipping_methods,
    business_shipping_international_shipping,
    business_shipping_local_delivery,

    source_name,
    source_acronym,
):
    item = {
        'business_is_category_herbs': business_is_category_herbs,

        'business_label': business_label,
        'business_name': business_name,
        'business_name_official': business_name_official,
        'business_name_legal': business_name_legal,
        'business_name_trade': business_name_trade,
        'business_slogan': business_slogan,
        'business_description': business_description,
        'business_description_short': business_description_short,
        'business_founded_year': business_founded_year,
        'business_founding_story': business_founding_story,
        'business_founder_names': business_founder_names,
        'business_ownership_type': business_ownership_type,
        'business_company_type': business_company_type,
        'business_status': business_status,
        'business_mission': business_mission,
        'business_vision': business_vision,
        'business_core_values': business_core_values,
        ###
        'business_type_primary': business_type_primary,
        'business_type_secondary': business_type_secondary,
        'business_industry': business_industry,
        'business_niche': business_niche,
        'business_model': business_model,
        ###
        'business_website': business_website,
        'business_email': business_email,
        'business_email_customer_service': business_email_customer_service,
        'business_email_wholesale': business_email_wholesale,
        'business_email_media': business_email_media,
        'business_phone': business_phone,
        'business_whatsapp': business_whatsapp,
        'business_fax': business_fax,
        'business_contact_form': business_contact_form,
        ###
        'business_headquarters': business_headquarters,
        'business_address': business_address,
        'business_city': business_city,
        'business_state': business_state,
        'business_region': business_region,
        'business_country': business_country,
        'business_postal_code': business_postal_code,
        'business_latitude': business_latitude,
        'business_longitude': business_longitude,
        'business_additional_locations': business_additional_locations,
        'business_farm_locations': business_farm_locations,
        'business_nursery_locations': business_nursery_locations,
        'business_factory_locations': business_factory_locations,
        'business_laboratory_locations': business_laboratory_locations,
        'business_warehouse_locations': business_warehouse_locations,
        'business_retail_locations': business_retail_locations,
        ###
        'business_opening_hours': business_opening_hours,
        'business_seasonal_hours': business_seasonal_hours,
        'business_appointment_required': business_appointment_required,
        'business_walk_in_available': business_walk_in_available,
        'business_visitor_access': business_visitor_access,
        ###
        'business_medicinal_plants': business_medicinal_plants,
        'business_primary_medicinal_plants': business_primary_medicinal_plants,
        'business_specialty_plants': business_specialty_plants,
        'business_native_plants': business_native_plants,
        'business_rare_plants': business_rare_plants,
        'business_medicinal_plant_categories': business_medicinal_plant_categories,
        'business_botanical_collection_size': business_botanical_collection_size,
        ###
        'business_grows': business_grows,
        'business_cultivates': business_cultivates,
        'business_propagates': business_propagates,
        'business_researches': business_researches,
        'business_sells': business_sells,
        'business_distributes': business_distributes,
        'business_exports': business_exports,
        'business_imports': business_imports,
        'business_wild_harvests': business_wild_harvests,
        'business_conserves': business_conserves,
        'business_teaches': business_teaches,
        'business_uses_in_products': business_uses_in_products,
        ###
        'business_products': business_products,
        'business_product_categories': business_product_categories,
        'business_flagship_products': business_flagship_products,
        'business_product_forms': business_product_forms,
        'business_herbal_teas': business_herbal_teas,
        'business_tinctures': business_tinctures,
        'business_extracts': business_extracts,
        'business_essential_oils': business_essential_oils,
        'business_capsules': business_capsules,
        'business_powders': business_powders,
        'business_dried_herbs': business_dried_herbs,
        'business_fresh_herbs': business_fresh_herbs,
        'business_seeds': business_seeds,
        'business_seedlings': business_seedlings,
        'business_roots': business_roots,
        'business_bark': business_bark,
        'business_flowers': business_flowers,
        'business_fruits': business_fruits,
        'business_resins': business_resins,
        'business_cosmetics': business_cosmetics,
        'business_soaps': business_soaps,
        'business_creams': business_creams,
        'business_salves': business_salves,
        'business_syrups': business_syrups,
        ###
        'business_botanical_name': business_botanical_name,
        'business_common_name': business_common_name,
        'business_plant_part': business_plant_part,
        'business_extraction_method': business_extraction_method,
        'business_preparation_method': business_preparation_method,
        'business_ingredients': business_ingredients,
        'business_packaging': business_packaging,
        'business_package_sizes': business_package_sizes,
        'business_concentration': business_concentration,
        'business_organic_product': business_organic_product,
        'business_private_label': business_private_label,
        'business_wholesale': business_wholesale,
        'business_retail': business_retail,
        ###
        'business_herbal_consultation': business_herbal_consultation,
        'business_herbal_clinic': business_herbal_clinic,
        'business_medicinal_plant_consulting': business_medicinal_plant_consulting,
        'business_plant_identification': business_plant_identification,
        'business_botanical_identification': business_botanical_identification,
        'business_cultivation_consulting': business_cultivation_consulting,
        'business_contract_growing': business_contract_growing,
        'business_contract_manufacturing': business_contract_manufacturing,
        'business_private_label_manufacturing': business_private_label_manufacturing,
        'business_extraction_services': business_extraction_services,
        'business_drying_services': business_drying_services,
        'business_milling': business_milling,
        'business_grinding': business_grinding,
        'business_packaging_service': business_packaging_service,
        'business_export_services': business_export_services,
        'business_laboratory_testing': business_laboratory_testing,
        'business_formulation': business_formulation,
        'business_research_services': business_research_services,
        'business_education': business_education,
        'business_workshops': business_workshops,
        'business_courses': business_courses,
        'business_farm_tours': business_farm_tours,
        'business_botanical_tours': business_botanical_tours,
        ###
        'business_cultivation_methods': business_cultivation_methods,
        'business_organic_cultivation': business_organic_cultivation,
        'business_regenerative': business_regenerative,
        'business_biodynamic': business_biodynamic,
        'business_permaculture': business_permaculture,
        'business_agroforestry': business_agroforestry,
        'business_greenhouse': business_greenhouse,
        'business_indoor': business_indoor,
        'business_outdoor': business_outdoor,
        'business_wild_harvesting': business_wild_harvesting,
        'business_sustainable_wild_harvesting': business_sustainable_wild_harvesting,
        'business_propagation_methods': business_propagation_methods,
        'business_irrigation': business_irrigation,
        'business_fertilization': business_fertilization,
        'business_soil_management': business_soil_management,
        'business_pest_management': business_pest_management,
        'business_harvest_methods': business_harvest_methods,
        'business_harvest_season': business_harvest_season,
        ###
        'business_manufacturing': business_manufacturing,
        'business_processing': business_processing,
        'business_extraction': business_extraction,
        'business_distillation': business_distillation,
        'business_fermentation': business_fermentation,
        'business_drying': business_drying,
        'business_manufacturing_milling': business_manufacturing_milling,
        'business_manufacturing_grinding': business_manufacturing_grinding,
        'business_blending': business_blending,
        'business_manufacturing_formulation': business_manufacturing_formulation,
        'business_encapsulation': business_encapsulation,
        'business_manufacturing_packaging': business_manufacturing_packaging,
        'business_quality_testing': business_quality_testing,
        'business_batch_testing': business_batch_testing,
        'business_traceability': business_traceability,
        ###
        'business_facilities_farms': business_facilities_farms,
        'business_facilities_nurseries': business_facilities_nurseries,
        'business_facilities_laboratories': business_facilities_laboratories,
        'business_facilities_factories': business_facilities_factories,
        'business_facilities_warehouses': business_facilities_warehouses,
        'business_facilities_botanical_gardens': business_facilities_botanical_gardens,
        'business_facilities_greenhouses': business_facilities_greenhouses,
        'business_facilities_visitor_centers': business_facilities_visitor_centers,
        'business_facilities_research_centers': business_facilities_research_centers,
        'business_facilities_education_centers': business_facilities_education_centers,
        'business_facilities_clinics': business_facilities_clinics,
        'business_facilities_retail_stores': business_facilities_retail_stores,
        ###
        'business_certifications_certifications': business_certifications_certifications,
        'business_certifications_certification_name': business_certifications_certification_name,
        'business_certifications_certification_number': business_certifications_certification_number,
        'business_certifications_issuing_organization': business_certifications_issuing_organization,
        'business_certifications_issue_date': business_certifications_issue_date,
        'business_certifications_expiry_date': business_certifications_expiry_date,
        'business_certifications_certification_scope': business_certifications_certification_scope,
        ###
        'business_quality_quality_control': business_quality_quality_control,
        'business_quality_laboratory_testing': business_quality_laboratory_testing,
        'business_quality_batch_testing': business_quality_batch_testing,
        'business_quality_third_party_testing': business_quality_third_party_testing,
        'business_quality_traceability': business_quality_traceability,
        'business_quality_quality_management_system': business_quality_quality_management_system,
        ###
        'business_sustainability_sustainability_policy': business_sustainability_sustainability_policy,
        'business_sustainability_conservation': business_sustainability_conservation,
        'business_sustainability_biodiversity': business_sustainability_biodiversity,
        'business_sustainability_regenerative_agriculture': business_sustainability_regenerative_agriculture,
        'business_sustainability_ethical_sourcing': business_sustainability_ethical_sourcing,
        'business_sustainability_fair_trade': business_sustainability_fair_trade,
        'business_sustainability_community_projects': business_sustainability_community_projects,
        'business_sustainability_indigenous_partnerships': business_sustainability_indigenous_partnerships,
        'business_sustainability_local_sourcing': business_sustainability_local_sourcing,
        'business_sustainability_recyclable_packaging': business_sustainability_recyclable_packaging,
        'business_sustainability_carbon_reduction': business_sustainability_carbon_reduction,
        'business_sustainability_water_conservation': business_sustainability_water_conservation,
        ###
        'business_research_research_programs': business_research_research_programs,
        'business_research_research_projects': business_research_research_projects,
        'business_research_publications': business_research_publications,
        'business_research_patents': business_research_patents,
        'business_research_university_partnerships': business_research_university_partnerships,
        'business_research_clinical_trials': business_research_clinical_trials,
        'business_research_ethnobotanical_research': business_research_ethnobotanical_research,
        'business_research_pharmacognosy': business_research_pharmacognosy,
        'business_research_phytochemistry': business_research_phytochemistry,
        'business_research_plant_breeding': business_research_plant_breeding,
        ###
        'business_education_courses': business_education_courses,
        'business_education_workshops': business_education_workshops,
        'business_education_webinars': business_education_webinars,
        'business_education_apprenticeships': business_education_apprenticeships,
        'business_education_lectures': business_education_lectures,
        'business_education_botanical_walks': business_education_botanical_walks,
        'business_education_farm_tours': business_education_farm_tours,
        'business_education_certifications_offered': business_education_certifications_offered,
        ###
        'business_traditional_medicine_systems_ayurveda': business_traditional_medicine_systems_ayurveda,
        'business_traditional_medicine_systems_traditional_chinese_medicine': business_traditional_medicine_systems_traditional_chinese_medicine,
        'business_traditional_medicine_systems_western_herbalism': business_traditional_medicine_systems_western_herbalism,
        'business_traditional_medicine_systems_unani': business_traditional_medicine_systems_unani,
        'business_traditional_medicine_systems_kampo': business_traditional_medicine_systems_kampo,
        'business_traditional_medicine_systems_tibetan_medicine': business_traditional_medicine_systems_tibetan_medicine,
        'business_traditional_medicine_systems_indigenous_medicine': business_traditional_medicine_systems_indigenous_medicine,
        'business_traditional_medicine_systems_african_traditional_medicine': business_traditional_medicine_systems_african_traditional_medicine,
        ###
        'business_expertise_expertise_topics': business_expertise_expertise_topics,
        'business_expertise_medicinal_plant_cultivation': business_expertise_medicinal_plant_cultivation,
        'business_expertise_herbal_formulation': business_expertise_herbal_formulation,
        'business_expertise_ethnobotany': business_expertise_ethnobotany,
        'business_expertise_pharmacognosy': business_expertise_pharmacognosy,
        'business_expertise_botanical_identification': business_expertise_botanical_identification,
        'business_expertise_herbal_medicine': business_expertise_herbal_medicine,
        'business_expertise_conservation': business_expertise_conservation,
        'business_expertise_plant_propagation': business_expertise_plant_propagation,
        ###
        'business_people_founders': business_people_founders,
        'business_people_owners': business_people_owners,
        'business_people_ceo': business_people_ceo,
        'business_people_president': business_people_president,
        'business_people_director': business_people_director,
        'business_people_botanists': business_people_botanists,
        'business_people_herbalists': business_people_herbalists,
        'business_people_researchers': business_people_researchers,
        'business_people_agronomists': business_people_agronomists,
        'business_people_pharmacists': business_people_pharmacists,
        'business_people_educators': business_people_educators,
        'business_people_laboratory_directors': business_people_laboratory_directors,
        'business_people_farm_managers': business_people_farm_managers,

        'business_markets_customer_types': business_markets_customer_types,
        'business_markets_industries_served': business_markets_industries_served,
        'business_markets_export_markets': business_markets_export_markets,
        'business_markets_import_markets': business_markets_import_markets,
        'business_markets_countries_served': business_markets_countries_served,
        'business_markets_regions_served': business_markets_regions_served,
        'business_markets_international_shipping': business_markets_international_shipping,
        'business_markets_wholesale_available': business_markets_wholesale_available,
        'business_markets_retail_available': business_markets_retail_available,
        'business_markets_private_label_available': business_markets_private_label_available,

        'business_online_presence_facebook': business_online_presence_facebook,
        'business_online_presence_instagram': business_online_presence_instagram,
        'business_online_presence_linkedin': business_online_presence_linkedin,
        'business_online_presence_youtube': business_online_presence_youtube,
        'business_online_presence_x': business_online_presence_x,
        'business_online_presence_pinterest': business_online_presence_pinterest,
        'business_online_presence_tiktok': business_online_presence_tiktok,
        'business_online_presence_github': business_online_presence_github,
        'business_online_presence_wikipedia': business_online_presence_wikipedia,

        'business_awards_awards': business_awards_awards,
        'business_awards_award_name': business_awards_award_name,
        'business_awards_award_year': business_awards_award_year,
        'business_awards_awarding_organization': business_awards_awarding_organization,

        'business_memberships_professional_associations': business_memberships_professional_associations,
        'business_memberships_industry_memberships': business_memberships_industry_memberships,
        'business_memberships_botanical_societies': business_memberships_botanical_societies,
        'business_memberships_herbal_associations': business_memberships_herbal_associations,

        'business_policies_privacy_policy': business_policies_privacy_policy,
        'business_policies_shipping_policy': business_policies_shipping_policy,
        'business_policies_returns_policy': business_policies_returns_policy,
        'business_policies_refund_policy': business_policies_refund_policy,
        'business_policies_sustainability_policy': business_policies_sustainability_policy,
        'business_policies_accessibility_policy': business_policies_accessibility_policy,

        'business_languages_languages': business_languages_languages,
        'business_languages_multilingual_support': business_languages_multilingual_support,

        'business_commerce_accepted_payment_methods': business_commerce_accepted_payment_methods,
        'business_commerce_currencies': business_commerce_currencies,
        'business_commerce_online_store': business_commerce_online_store,
        'business_commerce_ecommerce': business_commerce_ecommerce,

        'business_shipping_shipping_countries': business_shipping_shipping_countries,
        'business_shipping_shipping_methods': business_shipping_shipping_methods,
        'business_shipping_international_shipping': business_shipping_international_shipping,
        'business_shipping_local_delivery': business_shipping_local_delivery,

        'source_name': source_name,
        'source_acronym': source_acronym,
    }
    return item

