data = [
    {
        'field_name': 'business_is_category_herbs',
        'field_query': 'is mainly about medicinal plants', 
        'field_description': '''that this business is a seller, grower, user, or anything else related to herbs predominantly as their products and core business''', 
        'field_type': 'bool',
        'field_section': 'identity',
    },
    {
        'field_name': 'business_gmap_name_raw',
        'field_query': '', 
        'field_description': '''''', 
        'field_type': 'text',
        'field_section': 'identity',
    },
    {
        'field_name': 'business_name_raw',
        'field_query': 'business name', 
        'field_description': '''business name as shown on the website''', 
        'field_type': 'text',
        'field_section': 'identity',
    },
    {
        'field_name': 'business_name_official',
        'field_query': 'official business name', 
        'field_description': '''Official business name exactly as shown on the website''', 
        'field_type': 'text',
        'field_section': 'identity',
    },
    {
        'field_name': 'business_slogan',
        'field_query': 'business slogan', 
        'field_description': '''Official company slogan or tagline''', 
        'field_type': 'text',
        'field_section': 'identity',
    },
    {
        'field_name': 'business_website',
        'field_query': 'business website', 
        'field_description': '''The official website URL of the business. Extract the primary canonical domain used by the organization (e.g., https://www.example.com).''', 
        'field_type': 'text',
        'field_section': 'identity',
    },
    {
        'field_name': 'business_address',
        'field_query': 'business address', 
        'field_description': '''The complete street address of the business's primary location, including building number, street name, and other published address details.''', 
        'field_type': 'text',
        'field_section': 'location',
    },
    {
        'field_name': 'business_phone',
        'field_query': 'business phone', 
        'field_description': '''The primary business telephone number for customer inquiries. Preserve the international dialing code when available.''',
        'field_type': 'text',
        'field_section': 'contact',
    },
    {
        'field_name': 'business_rating',
        'field_query': '', 
        'field_description': '''''',
        'field_type': 'text',
        'field_section': 'identity',
    },
    {
        'field_name': 'business_reviews_num',
        'field_query': '', 
        'field_description': '''''',
        'field_type': 'text',
        'field_section': 'identity',
    },
]
